DROP TABLE IF EXISTS `CLIENTACCOUNT_PRODUCT`;
DROP TABLE IF EXISTS `DISCOUNT`;
DROP TABLE IF EXISTS `PRODUCT`;
DROP TABLE IF EXISTS `СATEGORY`;
DROP TABLE IF EXISTS `CLIENTACCOUNT`;


CREATE CACHED TABLE CLIENTACCOUNT(
    "ID" BIGINT,
    "AMOUNTOFMONEY" DECIMAL(19, 2),
    "EMAIL" VARCHAR(255),
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255)
);



CREATE CACHED TABLE "PUBLIC"."СATEGORY"(
    "ID" INTEGER NOT NULL,
    "NAME" VARCHAR(255)
);

CREATE CACHED TABLE "PUBLIC"."PRODUCT"(
    "ID" INTEGER DEFAULT NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PRICE" DECIMAL(19, 2),
    "CATEGORY_ID" INTEGER
);  

CREATE CACHED TABLE "PUBLIC"."DISCOUNT"(
    "ID" INTEGER NOT NULL,
    "DISCOUNTPERCENTAGE" INTEGER NOT NULL,
    "PRODUCT_ID" INTEGER
);

CREATE CACHED TABLE "PUBLIC"."CLIENTACCOUNT_PRODUCT"(
    "CLIENTACCOUNT_ID" BIGINT NOT NULL,
    "PRODUCT_ID" INTEGER NOT NULL
);  



ALTER TABLE "PUBLIC"."СATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");            
ALTER TABLE "PUBLIC"."CLIENTACCOUNT_PRODUCT" ADD CONSTRAINT "PUBLIC"."FK7VQEO1XKP7XOVTX7NG6NBREBW" FOREIGN KEY("CLIENTACCOUNT_ID") REFERENCES "PUBLIC"."CLIENTACCOUNT"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FK113GXYHC4OEOYUNHQ6GI7Q5QS" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."СATEGORY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CLIENTACCOUNT_PRODUCT" ADD CONSTRAINT "PUBLIC"."FK5IY9843UJNE42OJP7AEP0HFNH" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."DISCOUNT" ADD CONSTRAINT "PUBLIC"."FKN9PX36HJJPHWUN248SL5KX9YB" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK; 



INSERT INTO CLIENTACCOUNT (ID, FIRST_NAME, LAST_NAME, EMAIL, AMOUNTOFMONEY) VALUES (1, 'Viacheslav', 'Kozlov', 'viacheslav.kozlov@gmail.com', 100000);

INSERT INTO СATEGORY (ID, NAME) VALUES (1, 'phones');
INSERT INTO СATEGORY (ID, NAME) VALUES (2, 'laptops');

INSERT INTO PRODUCT VALUES(1, 'cтаньте ближе к тому, что важно для вас, c 5.9-дюймовом безграничным U-экраном Galaxy A40.', 'Samsung Galaxy A40', 4799, 1);
INSERT INTO PRODUCT VALUES(2, 'Уверенность и комфорт при выполнении повседневных задач', 'HP Pavilion Gaming 15-cx0033ua', 19999, 2);
INSERT INTO PRODUCT VALUES(3, 'Huawei P30 Lite', 'Huawei P30 Lite', 5299, 1);
INSERT INTO PRODUCT VALUES(4, 'Prestigio Muze J5 5524 Duo Dark Night', 'Prestigio Muze J5 5524 Duo Dark Night', 1299, 1);

--INSERT INTO DISCOUNT (ID, DISCOUNTPERCENTAGE, PRODUCT_ID) VALUES (1, 20, 1);
--INSERT INTO DISCOUNT (ID, DISCOUNTPERCENTAGE, PRODUCT_ID) VALUES (2, 10, 3);
--INSERT INTO DISCOUNT (ID, DISCOUNTPERCENTAGE, PRODUCT_ID) VALUES (3, 15, 2);
--INSERT INTO DISCOUNT (ID, DISCOUNTPERCENTAGE, PRODUCT_ID) VALUES (4, 5, 5);
